export interface ToolMeta {
  slug: string
  name: string
  description: string
  category: string
  keywords: string[]
}

export const tools: ToolMeta[] = [
  { slug: 'json-formatter', name: 'JSON Formatter & Validator', description: 'Format, validate, and beautify JSON data with syntax highlighting.', category: 'Formatter', keywords: ['json formatter online', 'json validator', 'json beautifier'] },
  { slug: 'base64-encode-decode', name: 'Base64 Encode/Decode', description: 'Encode text to Base64 or decode Base64 back to plain text.', category: 'Encoder', keywords: ['base64 decode', 'base64 encode online'] },
  { slug: 'url-encode-decode', name: 'URL Encode/Decode', description: 'Encode or decode URL components for safe transmission.', category: 'Encoder', keywords: ['url encoder', 'url decode online'] },
  { slug: 'jwt-decoder', name: 'JWT Decoder', description: 'Decode and inspect JSON Web Token header and payload.', category: 'Decoder', keywords: ['jwt decode online', 'jwt parser'] },
  { slug: 'uuid-generator', name: 'UUID Generator', description: 'Generate random UUID v4 identifiers instantly.', category: 'Generator', keywords: ['uuid generator', 'guid generator'] },
  { slug: 'hash-generator', name: 'Hash Generator', description: 'Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from text.', category: 'Crypto', keywords: ['sha256 hash generator', 'md5 generator'] },
  { slug: 'regex-tester', name: 'Regex Tester', description: 'Test regular expressions against sample text with match highlighting.', category: 'Tester', keywords: ['regex tester', 'regex101 alternative'] },
  { slug: 'unix-timestamp-converter', name: 'Unix Timestamp Converter', description: 'Convert Unix timestamps to human-readable dates and vice versa.', category: 'Converter', keywords: ['unix timestamp converter', 'epoch converter'] },
  { slug: 'color-converter', name: 'Color Converter', description: 'Convert colors between HEX, RGB, and HSL formats.', category: 'Converter', keywords: ['hex to rgb', 'color converter'] },
  { slug: 'lorem-ipsum-generator', name: 'Lorem Ipsum Generator', description: 'Generate placeholder text in paragraphs, sentences, or words.', category: 'Generator', keywords: ['lorem ipsum generator', 'dummy text generator'] },
  { slug: 'password-generator', name: 'Password Generator', description: 'Generate secure random passwords with customizable length and characters.', category: 'Generator', keywords: ['password generator', 'random password'] },
  { slug: 'markdown-preview', name: 'Markdown Preview', description: 'Write Markdown and see a live rendered preview side by side.', category: 'Formatter', keywords: ['markdown preview online', 'markdown editor'] },
  { slug: 'html-entity-encode-decode', name: 'HTML Entity Encode/Decode', description: 'Encode special characters to HTML entities or decode them back.', category: 'Encoder', keywords: ['html entity decoder', 'html encode'] },
  { slug: 'css-minifier', name: 'CSS Minifier', description: 'Minify CSS code by removing whitespace and comments.', category: 'Minifier', keywords: ['css minifier', 'css compressor'] },
  { slug: 'js-minifier', name: 'JavaScript Minifier', description: 'Minify JavaScript code by removing whitespace and shortening syntax.', category: 'Minifier', keywords: ['js minifier online', 'javascript compressor'] },
  { slug: 'sql-formatter', name: 'SQL Formatter', description: 'Format and beautify SQL queries for better readability.', category: 'Formatter', keywords: ['sql formatter', 'sql beautifier'] },
  { slug: 'cron-expression-generator', name: 'Cron Expression Generator', description: 'Build cron expressions visually with a human-readable preview.', category: 'Generator', keywords: ['cron expression generator', 'crontab guru'] },
  { slug: 'gitignore-generator', name: '.gitignore Generator', description: 'Generate .gitignore files for popular languages and frameworks.', category: 'Generator', keywords: ['gitignore generator', 'gitignore template'] },
  { slug: 'diff-checker', name: 'Diff Checker', description: 'Compare two texts and see the differences highlighted line by line.', category: 'Tester', keywords: ['diff checker online', 'text compare'] },
  { slug: 'json-to-csv', name: 'JSON to CSV Converter', description: 'Convert JSON arrays to CSV format for spreadsheet use.', category: 'Converter', keywords: ['json to csv', 'json csv converter'] },
  { slug: 'qr-code-generator', name: 'QR Code Generator', description: 'Generate QR codes from any text or URL instantly.', category: 'Generator', keywords: ['qr code generator', 'free qr code'] },
  { slug: 'slug-generator', name: 'Slug Generator', description: 'Convert text to URL-friendly slugs for SEO-friendly URLs.', category: 'Generator', keywords: ['slug generator', 'url slug converter'] },
  { slug: 'word-counter', name: 'Word Counter', description: 'Count words, characters, sentences, paragraphs, and estimate reading time.', category: 'Tester', keywords: ['word counter online', 'character counter'] },
  { slug: 'text-case-converter', name: 'Text Case Converter', description: 'Convert text between camelCase, snake_case, kebab-case, PascalCase, and more.', category: 'Converter', keywords: ['text case converter', 'camelcase converter'] },
  { slug: 'json-to-typescript', name: 'JSON to TypeScript', description: 'Generate TypeScript interfaces from JSON data automatically.', category: 'Generator', keywords: ['json to typescript', 'json to interface'] },
  { slug: 'image-to-base64', name: 'Image to Base64', description: 'Convert images to Base64 data URI strings for embedding in code.', category: 'Converter', keywords: ['image to base64', 'image encoder'] },
  { slug: 'tailwind-colors', name: 'Tailwind CSS Colors', description: 'Browse and copy all Tailwind CSS color palette values.', category: 'Reference', keywords: ['tailwind colors', 'tailwind color palette'] },
  { slug: 'chmod-calculator', name: 'Chmod Calculator', description: 'Calculate Unix file permissions in octal and symbolic notation.', category: 'Calculator', keywords: ['chmod calculator', 'permission calculator'] },
  { slug: 'yaml-json', name: 'YAML ↔ JSON Converter', description: 'Convert between YAML and JSON formats instantly.', category: 'Converter', keywords: ['yaml to json', 'json to yaml'] },
  { slug: 'csv-to-json', name: 'CSV to JSON', description: 'Convert CSV data to JSON array format.', category: 'Converter', keywords: ['csv to json', 'csv converter'] },
  { slug: 'number-base-converter', name: 'Number Base Converter', description: 'Convert numbers between binary, octal, decimal, and hexadecimal.', category: 'Converter', keywords: ['binary to decimal', 'hex converter', 'number base converter'] },
  { slug: 'http-status-codes', name: 'HTTP Status Codes', description: 'Searchable reference for all HTTP status codes with descriptions.', category: 'Reference', keywords: ['http status codes', 'http response codes'] },
  { slug: 'regex-escape', name: 'Regex Escape', description: 'Escape special regex characters in a string for literal matching.', category: 'Encoder', keywords: ['regex escape online', 'escape regex characters'] },
  { slug: 'html-to-markdown', name: 'HTML to Markdown', description: 'Convert HTML markup to clean Markdown syntax.', category: 'Converter', keywords: ['html to markdown', 'html to md'] },
  { slug: 'markdown-to-html', name: 'Markdown to HTML', description: 'Convert Markdown text to HTML output.', category: 'Converter', keywords: ['markdown to html', 'md to html'] },
  { slug: 'js-object-to-json', name: 'JS Object to JSON', description: 'Convert JavaScript object literals to valid JSON.', category: 'Converter', keywords: ['js object to json', 'javascript to json'] },
  { slug: 'json-path-finder', name: 'JSON Path Finder', description: 'Explore JSON structure and find paths to every value.', category: 'Tester', keywords: ['json path finder', 'jsonpath online'] },
  { slug: 'text-diff-word', name: 'Word-Level Diff', description: 'Compare texts and highlight differences at the word level.', category: 'Tester', keywords: ['word diff', 'word level comparison'] },
  { slug: 'json-tree-viewer', name: 'JSON Tree Viewer', description: 'Visualize JSON data as an interactive collapsible tree.', category: 'Formatter', keywords: ['json viewer', 'json tree', 'json explorer'] },
  { slug: 'meta-tag-generator', name: 'Meta Tag Generator', description: 'Generate HTML meta tags, Open Graph, and Twitter Card tags for SEO.', category: 'Generator', keywords: ['meta tag generator', 'og tag generator', 'seo tags'] },
  { slug: 'og-preview', name: 'Open Graph Preview', description: 'Preview how your page looks when shared on Facebook, LinkedIn, and X.', category: 'Tester', keywords: ['og preview', 'open graph preview', 'social share preview'] },
  { slug: 'svg-to-css', name: 'SVG to CSS Background', description: 'Convert SVG code to a CSS background-image data URI.', category: 'Converter', keywords: ['svg to css', 'svg background css', 'svg data uri'] },
  { slug: 'tailwind-to-css', name: 'Tailwind to CSS', description: 'Convert Tailwind CSS utility classes to plain CSS properties.', category: 'Converter', keywords: ['tailwind to css', 'tailwind converter'] },
  { slug: 'favicon-generator', name: 'Favicon Generator', description: 'Generate favicon PNG files from text or emoji with custom colors.', category: 'Generator', keywords: ['favicon generator', 'favicon from text', 'emoji favicon'] },
  { slug: 'jwt-generator', name: 'JWT Generator', description: 'Generate JWT tokens with custom header and payload for testing.', category: 'Generator', keywords: ['jwt generator', 'jwt token generator', 'create jwt'] },
  { slug: 'user-agent-parser', name: 'User Agent Parser', description: 'Parse user agent strings to detect browser, OS, and device type.', category: 'Tester', keywords: ['user agent parser', 'ua parser', 'detect browser'] },
  { slug: 'placeholder-image', name: 'Placeholder Image Generator', description: 'Generate custom placeholder images with specified dimensions and colors.', category: 'Generator', keywords: ['placeholder image', 'dummy image generator'] },
  { slug: 'bcrypt-generator', name: 'Bcrypt Hash Generator', description: 'Generate bcrypt-format password hashes with configurable rounds.', category: 'Crypto', keywords: ['bcrypt generator', 'bcrypt hash online', 'password hash'] },
  { slug: 'toml-to-json', name: 'TOML to JSON', description: 'Convert TOML configuration files to JSON format.', category: 'Converter', keywords: ['toml to json', 'toml converter', 'toml parser'] },
  { slug: 'ip-info', name: 'IP Address Info', description: 'Show your current public IP address, location, ISP, and timezone.', category: 'Reference', keywords: ['what is my ip', 'ip address lookup', 'my ip'] },
  { slug: 'code-to-image', name: 'Code to Image', description: 'Turn code snippets into beautiful shareable PNG images.', category: 'Generator', keywords: ['code to image', 'code screenshot', 'carbon alternative'] },
  { slug: 'epoch-countdown', name: 'Epoch Countdown Timer', description: 'Live Unix epoch clock with countdown timer to any date.', category: 'Converter', keywords: ['epoch timer', 'countdown timer', 'unix clock'] },
  { slug: 'box-shadow-generator', name: 'Box Shadow Generator', description: 'Generate CSS box-shadow with visual preview and live controls.', category: 'Generator', keywords: ['box shadow generator', 'css shadow generator'] },
  { slug: 'gradient-generator', name: 'CSS Gradient Generator', description: 'Create linear and radial CSS gradients with color picker and angle control.', category: 'Generator', keywords: ['css gradient generator', 'gradient maker'] },
  { slug: 'flexbox-generator', name: 'Flexbox Generator', description: 'Visual flexbox layout builder with live preview and CSS output.', category: 'Generator', keywords: ['flexbox generator', 'flex layout builder'] },
  { slug: 'env-to-json', name: '.env ↔ JSON Converter', description: 'Convert between .env files and JSON format.', category: 'Converter', keywords: ['env to json', 'dotenv converter', 'json to env'] },
  { slug: 'text-to-binary', name: 'Text to Binary', description: 'Convert text to binary representation and back.', category: 'Encoder', keywords: ['text to binary', 'binary converter', 'binary to text'] },
  { slug: 'ascii-art-generator', name: 'ASCII Art Generator', description: 'Convert text into ASCII art using canvas rendering.', category: 'Generator', keywords: ['ascii art generator', 'text to ascii', 'ascii art'] },
  { slug: 'docker-run-to-compose', name: 'Docker Run to Compose', description: 'Convert docker run commands to docker-compose.yml format.', category: 'Converter', keywords: ['docker run to compose', 'docker compose converter'] },
  { slug: 'nginx-config-generator', name: 'Nginx Config Generator', description: 'Generate Nginx reverse proxy configs with SSL, gzip, and caching.', category: 'Generator', keywords: ['nginx config generator', 'nginx reverse proxy'] },
  { slug: 'sql-to-mongodb', name: 'SQL to MongoDB', description: 'Convert SQL queries to MongoDB shell commands.', category: 'Converter', keywords: ['sql to mongodb', 'sql to mongo', 'mongo query converter'] },
  { slug: 'dns-lookup', name: 'DNS Lookup', description: 'Query DNS records (A, AAAA, MX, NS, TXT, CNAME) for any domain.', category: 'Reference', keywords: ['dns lookup', 'dns checker', 'domain dns records'] },
  { slug: 'ssl-checker', name: 'SSL Certificate Checker', description: 'Check SSL certificate validity, issuer, expiration, and protocol for any domain.', category: 'Tester', keywords: ['ssl checker', 'ssl certificate check', 'https checker'] },
]

export function getToolBySlug(slug: string): ToolMeta | undefined {
  return tools.find(t => t.slug === slug)
}
